defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/ruby:2.5.1-jessie-node

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - run:
          name: Bundle
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-server-dev-9.4
            bundle install
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    <<: *defaults
    environment:
      HEROKU_APP: "whatsapp-conversations"
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
